services:

  app:
    build: .
    container_name: nest-app
    restart: always
    env_file:
      - .env
    ports:
      - '3333:3333'
    command: yarn start:dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

