services:

  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4l9u2i7s
      - POSTGRES_DB=barbershop
    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
      - app-network
  app:
    build: .
    container_name: nest-app
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq
      - postgres
    ports:
      - '3333:3333'
    command: yarn start:dev
    networks:
      - app-network

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    command: redis-server --requirepass senha_do_redis
    ports:
      - '6379:6379'
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - '5672:5672'
      - '15672:15672' # painel web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


volumes:
  pgdata: