services:

  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4l9u2i7s
      - POSTGRES_DB=barbershop
    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
      - app-network
  app:
    build: .
    container_name: nest-app
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - '3333:3333'
    command: yarn start:dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


volumes:
  pgdata: