services:

  app:
    build: .
    container_name: nest-app
    restart: always
    env_file:
      - .env
    ports:
      - '3333:3333'
    command: yarn start:prod
    volumes:
      - .:/app
      - /app/node_modules # evita sobrescrever node_modules do container com do host
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

